language: generic
sudo: required
services:
        - docker

before_install:
        - docker build -t egorovforjob/react_travis_aws -f Dockerfile.dev .

script:
        - docker run -e CI=true egorovforjob/react_travis_aws npm run test -- --coverage
#
