language: generic
sudo: required
services:
        - docker

before_install:
        - docker build -t egorovforjob/react_travis_aws -f Dockerfile.dev .

script:
        - docker run -e CI=true egorovforjob/react_travis_aws npm run test

deploy:
        provider: elasticbeanstalk
        region: "eu-central-1"
        app: "react_travis_aws"
        env: "React_travis_aws-env"
        bucket_name: "elasticbeanstalk-eu-central-1-808319772349"
        bucket_path: "react_travis_aws"
        on:
                branch: master
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key: 
               secure: "$AWS_SECRET_KEY"
